'\" t
.\"     Title: caption-source-order
.\"    Author: [see the "AUTHOR(S)" section]
.\" Generator: acdc 0.1.0
.\"      Date: 2026-08-30
.\"    Manual: Caption checks
.\"    Source: acdc
.\"  Language: English
.\"
.TH "CAPTION\-SOURCE\-ORDER" "1" "2026-08-30" "acdc" "Caption checks"
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.ss \n[.ss] 0
.nh
.ad l
.de URL
\fI\\$2\fP <\\$1>\\$3
..
.als MTO URL
.if \n[.g] \{\
.  mso www.tmac
.  am URL
.    ad l
.  .
.  am MTO
.    ad l
.  .
.  LINKSTYLE blue R < >
.\}
.SH "NAME"
caption\-source\-order \- verify source\-position caption behavior
.SH "SYNOPSIS"
.sp
caption\-source\-order
.SH "DESCRIPTION"
.sp
.nr acdc-title-font \n[.f]
\fBBefore Figure 1. Before figure\f[\n[acdc-title-font]]
.br
.rr acdc-title-font
[before]
.sp
.nr acdc-title-font \n[.f]
\fBBefore Table 1. Before table\f[\n[acdc-title-font]]
.br
.rr acdc-title-font
.TS
allbox tab(:);
ltx.
Before table cell
.TE
.sp
.nr acdc-title-font \n[.f]
\fBBefore Example 2. Before outer example\f[\n[acdc-title-font]]
.br
.rr acdc-title-font
.RS 4
.sp
.nr acdc-title-font \n[.f]
\fBBefore Example 1. Before inner example\f[\n[acdc-title-font]]
.br
.rr acdc-title-font
.RS 4
.sp
Before inner example content.
.RE
.RE
.sp
.nr acdc-title-font \n[.f]
\fBBefore Listing 1. Before listing paragraph\f[\n[acdc-title-font]]
.br
.rr acdc-title-font
.if n .RS 4
.nf
.fam C
let before = 1;
.fam
.fi
.if n .RE
.sp
.nr acdc-title-font \n[.f]
\fBAfter Figure 2. After figure\f[\n[acdc-title-font]]
.br
.rr acdc-title-font
[after]
.sp
.nr acdc-title-font \n[.f]
\fBAfter Table 2. After table\f[\n[acdc-title-font]]
.br
.rr acdc-title-font
.TS
allbox tab(:);
ltx.
After table cell
.TE
.sp
.nr acdc-title-font \n[.f]
\fBAfter Example 3. After example\f[\n[acdc-title-font]]
.br
.rr acdc-title-font
.RS 4
.sp
After example content.
.RE
.sp
.nr acdc-title-font \n[.f]
\fBAfter Listing 2. After listing block\f[\n[acdc-title-font]]
.br
.rr acdc-title-font
.EX
let after = 2;
.EE
.sp
.nr acdc-title-font \n[.f]
\fBDisabled figure\f[\n[acdc-title-font]]
.br
.rr acdc-title-font
[disabled]
.sp
.nr acdc-title-font \n[.f]
\fBDisabled table\f[\n[acdc-title-font]]
.br
.rr acdc-title-font
.TS
allbox tab(:);
ltx.
Disabled table cell
.TE
.sp
.nr acdc-title-font \n[.f]
\fBDisabled example\f[\n[acdc-title-font]]
.br
.rr acdc-title-font
.RS 4
.sp
Disabled example content.
.RE
.sp
.nr acdc-title-font \n[.f]
\fBDisabled listing\f[\n[acdc-title-font]]
.br
.rr acdc-title-font
.EX
disabled listing content
.EE
.sp
.nr acdc-title-font \n[.f]
\fBCustom Figure: Custom figure\f[\n[acdc-title-font]]
.br
.rr acdc-title-font
[custom]
.sp
.nr acdc-title-font \n[.f]
\fBCustom Table: Custom table\f[\n[acdc-title-font]]
.br
.rr acdc-title-font
.TS
allbox tab(:);
ltx.
Custom table cell
.TE
.sp
.nr acdc-title-font \n[.f]
\fBCustom Example: Custom example\f[\n[acdc-title-font]]
.br
.rr acdc-title-font
.RS 4
.sp
Custom example content.
.RE
.sp
.nr acdc-title-font \n[.f]
\fBCustom Listing: Custom listing\f[\n[acdc-title-font]]
.br
.rr acdc-title-font
.EX
custom listing content
.EE
.sp
.nr acdc-title-font \n[.f]
\fBDocument:Document figure\f[\n[acdc-title-font]]
.br
.rr acdc-title-font
[document]
.sp
.nr acdc-title-font \n[.f]
\fBDocument:Document table\f[\n[acdc-title-font]]
.br
.rr acdc-title-font
.TS
allbox tab(:);
ltx.
Document table cell
.TE
.sp
.nr acdc-title-font \n[.f]
\fBDocument:Document example\f[\n[acdc-title-font]]
.br
.rr acdc-title-font
.RS 4
.sp
Document example content.
.RE
.sp
.nr acdc-title-font \n[.f]
\fBDocument:Document listing\f[\n[acdc-title-font]]
.br
.rr acdc-title-font
.EX
document listing content
.EE
.sp
.nr acdc-title-font \n[.f]
\fBRestored Figure 3. Restored figure\f[\n[acdc-title-font]]
.br
.rr acdc-title-font
[restored]
.sp
.nr acdc-title-font \n[.f]
\fBRestored Table 3. Restored table\f[\n[acdc-title-font]]
.br
.rr acdc-title-font
.TS
allbox tab(:);
ltx.
Restored table cell
.TE
.sp
.nr acdc-title-font \n[.f]
\fBRestored Example 4. Restored example\f[\n[acdc-title-font]]
.br
.rr acdc-title-font
.RS 4
.sp
Restored example content.
.RE
.sp
.nr acdc-title-font \n[.f]
\fBRestored Listing 3. Restored listing\f[\n[acdc-title-font]]
.br
.rr acdc-title-font
.EX
restored listing content
.EE
