'\" t
.\"     Title: mono-boundaries
.\"    Author: [see the "AUTHOR(S)" section]
.\" Generator: acdc 0.1.0
.\"      Date: 2026-10-02
.\"    Manual: Inline formatting boundaries
.\"    Source: acdc
.\"  Language: English
.\"
.TH "MONO\-BOUNDARIES" "1" "2026-10-02" "acdc" "Inline formatting boundaries"
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.ss \n[.ss] 0
.nh
.ad l
.de URL
\fI\\$2\fP <\\$1>\\$3
..
.als MTO URL
.if \n[.g] \{\
.  mso www.tmac
.  am URL
.    ad l
.  .
.  am MTO
.    ad l
.  .
.  LINKSTYLE blue R < >
.\}
.SH "NAME"
mono\-boundaries \- adjacent inline formatting
.SH "DESCRIPTION"
.sp
P01 \f(CRCode\fR\fBEnd\fR\&.
.sp
P02 \f(CRCode\fR\fBEnd\fR\&.
.sp
P03 `Code`\fIEnd\fR\&.
.sp
P04 `Code`\fIEnd\fR\&.
.sp
P05 \f(CRCode\fR\fBEnd\fR\&.
.sp
P06 \f(CRCode\fR\fBEnd\fR\&.
.sp
P07 \f(CRCode\fR_(End)\&.
.sp
P08 \f(CRCode\fR^(End)\&.
.sp
P09 \fBStart\fR\f(CRCode\fR\&.
.sp
P10 \fBStart\fR\f(CRCode\fR\&.
.sp
P11 \fIStart\fR`Code`.
.sp
P12 \fBStart\fR\f(CRCode\fR\&.
.sp
P13 \f(CRCode``Next\fR\&.
.sp
P14 `Code`word.
.sp
P15 word`Code`.
.sp
P16 ` Code`\fBEnd\fR\&.
.sp
P17 `Code `\fBEnd\fR\&.
.sp
P18 `Code\(cq\&.
.sp
P19 \f(CRCode\fR*End*.
.sp
P20 \f(CRCode\fR:End.
.sp
P21 \f(CRCode\fR😀.
.sp
P22 é`Code`.
.sp
P23 `Code`é.
.sp
P24 `Code`\fIsuffix\fR\&.
.sp
P25 `Code`_suffix.
.sp
P26 \f(CRCode\fR*suffix.
.sp
P27 \fBStart \f(CRCode\fB\fR\&.
.sp
P28 \fIStart `Code`\fR\&.
.sp
P29 \fBStart \f(CRCode\fB\fR\&.
.sp
P30 \f(CR\fBBold\f(CR\fR\fBEnd\fR\&.
.sp
P31 \f(CR\fR\fBEnd\fR\&.
.sp
P32 \f(CR\fR\fBEnd\fR\&.
.sp
P33 \f(CR\c
.URL "https://example.org" "\f(CRSite" "\f(CR\c"
\fR\fBEnd\fR\&.
.sp
P34 \f(CRCode\fR\fBEnd\fR\&.
.sp
P35 \fBStart\fR\f(CRCode\fR\&.
.sp
P36 \f(CRCode\fR \fBEnd\fR\&.
.sp
P37 \f(CRCode\fR\fBEnd\fR\&.
.sp
P38 `Code`\fBEnd\fR\&.
.sp
P39 `Code`**End**\&.
.sp
P40 \f(CRCode\fR
\fBEnd\fR\&.
.sp
P41 \f(CRCode\fR#suffix.
.sp
P42 `Code`\fIEnd\fR\fBTail\fR\&.
.sp
P43 \f(CRCode\fR\fBEnd\fR\f(CRNext\fR\&.
.sp
P44 \f(CRCode\fR\eEnd.
.sp
P45 \f(CRCode\fR=End.
.sp
P46 \f(CRCode\fR%End.
.sp
P47 prefix;`Code`\fBEnd\fR\&.
.sp
P48 prefix}`Code`\fBEnd\fR\&.
.sp
P49 prefix:`Code`\fBEnd\fR\&.
.sp
P50 <del>&amp;*bold*&amp;</del>\&.
.sp
P51 `Code`"End.
