'\" t
.\"     Title: linkstyle-test
.\"    Author: [see the "AUTHOR(S)" section]
.\" Generator: acdc 0.1.0
.\"      Date: 2025-06-01
.\"    Manual: Test Manual
.\"    Source: Test 1.0
.\"  Language: English
.\"
.TH "LINKSTYLE\-TEST" "1" "2025-06-01" "Test 1.0" "Test Manual"
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.ss \n[.ss] 0
.nh
.ad l
.de URL
\fI\\$2\fP <\\$1>\\$3
..
.als MTO URL
.if \n[.g] \{\
.  mso www.tmac
.  am URL
.    ad l
.  .
.  am MTO
.    ad l
.  .
.  LINKSTYLE bold B []
.\}
.SH "NAME"
linkstyle\-test \- test custom link style
.SH "SYNOPSIS"
.sp
\fBlinkstyle\-test\fP
.SH "DESCRIPTION"
.sp
Visit \c
.URL "https://example.com" "" ""
for details.
