'\" t
.\"     Title: prepared-attributes
.\"    Author: [see the "AUTHOR(S)" section]
.\" Generator: acdc 0.1.0
.\"      Date: 2026-10-02
.\"    Manual: \ \&
.\"    Source: \ \&
.\"  Language: English
.\"
.TH "PREPARED\-ATTRIBUTES" "1" "2026-10-02" "\ \&" "\ \&"
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.ss \n[.ss] 0
.nh
.ad l
.de URL
\fI\\$2\fP <\\$1>\\$3
..
.als MTO URL
.if \n[.g] \{\
.  mso www.tmac
.  am URL
.    ad l
.  .
.  am MTO
.    ad l
.  .
.  LINKSTYLE blue R < >
.\}
.SH "NAME"
prepared\-attributes \- formatted document attributes
.SH "SYNOPSIS"
.sp
\fBprepared\-attributes\fR
.SH "DESCRIPTION"
.sp
Frozen: \fBEarly\fR / \fBEarly\fR / \fBEarly\fR \(co / \fBLate\fR\&.
.sp
Alias: \fBBold\fR / \fBEarly\fR / [1] / \fBBody\fR / [2] / [3]\&.
.sp
Macros: \c
.URL "https://example.org" "Site" "\fR\c"
 / Term / [4] / [4]\&.
.sp
Empty: ** / **\&. Escaped: \fB{name}\fR\&.
.sp
Order: pass:q,c[*Escaped*] / pass:m,c[https://example.org[Escaped site]]\&. Partial: prefix pass:q[*Literal*].
.TS
allbox tab(:);
ltx ltx.
T{
.sp
Cell: \fBEarly\fR / \fBBold\fR / \fBEarly\fR / [5]\&.

T}:T{
.sp
Other: Late / \fBBody\fR\&.

T}
.TE
.sp
Unset: {bold} / \fBBold\fR / \fBEarly\fR / [6]\&.
.SH "INDEX"
.SS "T"
.RS 4
Term
.br
.RE
.SH "NOTES"
.IP [1] 4
Anonymous body.
.IP [2] 4
Anonymous body.
.IP [3] 4
Anonymous body.
.IP [4] 4
Named body.
.IP [5] 4
Anonymous body.
.IP [6] 4
Anonymous body.
