'\" t
."     Title: email-test(1)
."    Author: [see the "AUTHOR(S)" section]
." Generator: acdc 0.1.0
."      Date: 2025-01-20
."    Manual: \ \&
."    Source: \ \&
."  Language: English
."
.TH "EMAIL\-TEST" "1" "2025-01-20" "\ \&" "\ \&"
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.ss \n[.ss] 0
.\" Disable hyphenation
.nh
.\" Left-align only
.ad l
.\" URL/email macros
.de URL
\fI\\$2\fP <\\$1>\\$3
..
.als MTO URL
.if \n[.g] \{
.  mso www.tmac
.  am URL
.    ad l
.  .
.  am MTO
.    ad l
.  .
.  LINKSTYLE blue R < >
.\}
.SH "NAME"
email\-test \- test email autolink trailing punctuation
.SH "DESCRIPTION"
.PP
Contact \c
.MTO "user\(atexample.com" "" "."
.PP
In parentheses (\c
.MTO "user\(atexample.com" "" ")"
.PP
No trailing: \c
.MTO "user\(atexample.com" "" ""
.PP
URL should not capture: \(lahttps://example.com.\(ra
.PP
Multiple trailing: \c
.MTO "user\(atexample.com" "" ".,;"
.PP
In braces {\c
.MTO "user\(atexample.com" "" "}"
.PP
In quotes "\c
.MTO "user\(atexample.com" "" """
.PP
Exclamation: \c
.MTO "user\(atexample.com" "" "!"
.PP
Punct then bold: \c
.MTO "user\(atexample.com" "" ".\fBbold\fP" text
.PP
Space then text: \c
.MTO "user\(atexample.com" "" "" more text here
