'\" t
.\"     Title: index-terms-table-header
.\"    Author: [see the "AUTHOR(S)" section]
.\" Generator: acdc 0.1.0
.\"      Date: 2026-08-29
.\"    Manual: \ \&
.\"    Source: \ \&
.\"  Language: English
.\"
.TH "INDEX\-TERMS\-TABLE\-HEADER" "1" "2026-08-29" "\ \&" "\ \&"
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.ss \n[.ss] 0
.nh
.ad l
.de URL
\fI\\$2\fP <\\$1>\\$3
..
.als MTO URL
.if \n[.g] \{\
.  mso www.tmac
.  am URL
.    ad l
.  .
.  am MTO
.    ad l
.  .
.  LINKSTYLE blue R < >
.\}
.SH "NAME"
index\-terms\-table\-header \- index terms in table headers
.SH "DESCRIPTION"
.sp
\fBTable 1. Cataloged table\fP
.br
.TS
allbox tab(:);
ltB ltB
lt lt
lt lt
lt lt.
Key  :T{
Description with visible \fBheader\fP, shared term, and related material
T}
1:The body contains \&.
2:A second body row.
Footer :The non\-repeating footer contains a concealed term.
.TE
.sp
An occurrence after the table \&.
.SH "INDEX"
.SS "A"
.RS 4
after table
.br
.RE
.SS "B"
.RS 4
body term
.br
.RE
.SS "F"
.RS 4
footer term
.br
.RE
.SS "R"
.RS 4
Related header
.br
.RS 4
(see also Tables)
.br
.RE
.RE
.SS "S"
.RS 4
shared term
.br
.RE
.SS "T"
.RS 4
Tables
.br
.RS 4
Headers
.br
.RS 4
concealed
.br
.RE
.RE
table title
.br
.RE
.SS "V"
.RS 4
visible \fBheader\fP
.br
.RE
