'\" t
.\"     Title: inline-spacing
.\"    Author: [see the "AUTHOR(S)" section]
.\" Generator: acdc 0.1.0
.\"      Date: 2026-09-28
.\"    Manual: Spacing tests
.\"    Source: acdc
.\"  Language: English
.\"
.TH "INLINE\-SPACING" "1" "2026-09-28" "acdc" "Spacing tests"
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.ss \n[.ss] 0
.nh
.ad l
.de URL
\fI\\$2\fP <\\$1>\\$3
..
.als MTO URL
.if \n[.g] \{\
.  mso www.tmac
.  am URL
.    ad l
.  .
.  am MTO
.    ad l
.  .
.  LINKSTYLE blue R < >
.\}
.SH "NAME"
inline\-spacing \- preserve spaces around inline formatting
.SH "DESCRIPTION"
.sp
Copyright \fBBold\fR and \(co.
.sp
Registered \fIItalic\fR and \(rg.
.sp
Trademark \f(CRCode\fR and \(tm.
.sp
Hyphen \fBBold\fR \- dash.
.sp
Backslash \fBBold\fR path\eto\efile.
.sp
Quotes \fBBold\fR \(lqquoted\(rq\&.
.sp
Ellipsis \fBBold\fR .\|.\|. end.
.sp
Nested \fBBold \fIItalic\fB\fR and \(co.
.sp
Raw \fBBold\fR and \(co.
.sp
Adjacent \fBBold\fR\(co.
.sp
Multiple \fBBold\fR  spaces and \(co.
.sp
Wrapped plain
next line.
.sp
Wrapped symbol
next \(co line.
.sp
Wrapped indentation
next line \- normalized.
.sp
Protected period \fBBold\fR
\&.leading\-period
.sp
Protected apostrophe \fBBold\fR
\(aqleading\-apostrophe
.sp
Hard break \fBBold\fR
.br
next \(co line.
.sp
Formatted hard break before
.br
\fBBold\fR and \(co.
.sp
Marker hard break before
.br
[1] and \(co.
.sp
Raw hard break before
.br
next \(co.
.sp
Nonbreaking hard break before
.br
\ next \(co.
.sp
Anchor hard break before
.br
next \(co.
.sp
Hidden index hard break before
.br
next \(co.
.sp
Visible index hard break before
.br
Visible and \(co.
.sp
Link \c
.URL "https://example.org" "Example" "\fR\c"
 and \(co.
.sp
Note [2]
Reuse [2]\&.
.nf
  keep   spaces \(co
.fi
.SH "NOTES"
.IP [1] 4
Break note.
.IP [2] 4
\fBBold\fR and \(co.
