'\" t
.\"     Title: link-punctuation
.\"    Author: [see the "AUTHOR(S)" section]
.\" Generator: acdc 0.1.0
.\"      Date: 2026-10-02
.\"    Manual: Link punctuation
.\"    Source: acdc
.\"  Language: English
.\"
.TH "LINK\-PUNCTUATION" "1" "2026-10-02" "acdc" "Link punctuation"
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.ss \n[.ss] 0
.nh
.ad l
.de URL
\fI\\$2\fP <\\$1>\\$3
..
.als MTO URL
.if \n[.g] \{\
.  mso www.tmac
.  am URL
.    ad l
.  .
.  am MTO
.    ad l
.  .
.  LINKSTYLE blue R < >
.\}
.SH "NAME"
link\-punctuation \- preserve inline link boundaries
.SH "DESCRIPTION"
.sp
P01 \c
.URL "https://example.org" "Label" "\fR\c"
\&.
.sp
P02 \c
.URL "https://example.org" "Label" "\fR\c"
, next.
.sp
P03 (\c
.URL "https://example.org" "" "\fR\c"
).
.sp
P04 \c
.MTO "test\(atexample.org" "Mail" "\fR\c"
!
.sp
P05 \c
.MTO "test\(atexample.org" "" "\fR\c"
\&.
.sp
P06 \c
.URL "https://example.org" "Label" "\fR\c"
,;:!?
.sp
P07 \c
.URL "https://example.org" "Label" "\fR\c"
suffix.
.sp
P08 \c
.URL "https://example.org" "Label" "\fR\c"
 \fBbold\fR\&.
.sp
P09 \c
.URL "https://example.org" "Label" "\fR\c"
\fBbold\fR\&.
.sp
P10 \c
.URL "https://example.org" "Label" "\fR\c"
\&.
.sp
P11 \c
.URL "https://example.org" "Label" "\fR\c"
\&.
.sp
P12 \c
.URL "https://example.org" "Label" "\fR\c"
[1]\&.
.sp
P13 \c
.URL "https://example.org" "Label" "\fR\c"
\&.
.sp
P14 \c
.URL "https://example.org" "Label" "\fR\c"
\&.
.sp
P15 \c
.URL "https://example.org" "Label" "\fR\c"
»
.sp
P16 \c
.URL "https://example.org" "Label" "\fR\c"
\ next.
.sp
P17 \c
.URL "https://example.org" "Label" "\fR\c"

next line.
.sp
P18 \c
.URL "https://example.org" "Label" "\fR\c"

.br
next line.
.sp
P19 \fB\c
.URL "https://example.org" "\fBLabel" "\fB\c"
\&.\fR
.sp
P20 \c
.URL "manual.txt" "Manual" "\fR\c"
\&.
.sp
P21 \c
.URL "https://example.org" "" "\fR\c"
\&.
.sp
P22 \c
.URL "https://example.org" "A \(dqquote\(dq and \epath" "\fR\c"
\etail.
.sp
P23 \c
.URL "https://example.org" "Label" "\fR\c"
\c
.URL "https://second.example" "Second" "\fR\c"
\&.
.sp
P24 \c
.URL "https://example.org" "Label" "\fR\c"
 \c
.URL "https://second.example" "Second" "\fR\c"
\&.
.sp
P25 \c
.MTO "test\(atexample.org" "Mail" "\fR\c"
\(co.
.sp
P26 \c
.MTO "test\(atexample.org" "Mail" "\fR\c"
Word\&.
.sp
P27 \c
.MTO "test\(atexample.org" "Mail" "\fR\c"
 (C)\&.
.sp
P28 \c
.URL "https://example.org" "Label" "\fR\c"

.sp
Next paragraph.
.sp
P29 \c
.URL "https://example.org" "Label" "\fR\c"
 \fIitalic\fR and \f(CRcode\fR\&.
.sp
P30 \c
.MTO "test\(atexample.org" "Mail" "\fR\c"
! More.
.sp
P31 \c
.MTO "test\(atexample.org" "Mail" "\fR\c"
[1]\&.
.sp
P32 \c
.URL "https://example.org" "\fIQuoted label\fR" "\fR\c"
\&.
.sp
P33 (\c
.URL "https://example.org" "" "\fR\c"
)after.
.sp
P34 \c
.URL "https://example.org" "Label" "\fR\c"
\&.
.SH "NOTES"
.IP [1] 4
Note text.
