'\" t
.\"     Title: link-formatting
.\"    Author: [see the "AUTHOR(S)" section]
.\" Generator: acdc 0.1.0
.\"      Date: 2026-10-05
.\"    Manual: \ \&
.\"    Source: \ \&
.\"  Language: English
.\"
.TH "LINK\-FORMATTING" "1" "2026-10-05" "\ \&" "\ \&"
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.ss \n[.ss] 0
.nh
.ad l
.de URL
\fI\\$2\fP <\\$1>\\$3
..
.als MTO URL
.if \n[.g] \{\
.  mso www.tmac
.  am URL
.    ad l
.  .
.  am MTO
.    ad l
.  .
.  LINKSTYLE blue R < >
.\}
.SH "NAME"
link\-formatting \- preserve formatting and complete links
.SH "DESCRIPTION"
.sp
L01 \fBBefore \c
.URL "https://example.org/bold" "\fB\fBBold\fB after" "\fB\c"
 end\fR\&.
.sp
L02 \fIBefore \c
.URL "https://example.org/italic" "\fI\fIItalic\fI after" "\fI\c"
 end\fR\&.
.sp
L03 \f(CRBefore \c
.URL "https://example.org/code" "\f(CR\f(CRCode\f(CR after" "\f(CR\c"
 end\fR\&.
.sp
L04 \fBBefore \c
.URL "https://example.org/mark" "\fB\fBMarked\fB after" "\fB\c"
 end\fR\&.
.sp
L05 \fBBefore \c
.URL "manual.html" "\fB\fBManual\fB after" "\fB\c"
 end\fR\&.
.sp
L06 \fIBefore \c
.MTO "user\(atexample.org" "\fI\fIMail\fI after" "\fI\c"
 end\fR\&.
.sp
L07 \fIBefore \fIReference\fI after end\fR\&.
.sp
L08 \fBBefore \fBReference\fB after end\fR\&.
.sp
L09 \fBBefore \c
.URL "https://outer.example" "\fBBefore" "\fB \c"
\fB\c
.URL "https://outer.example" "\fBbold" "\fB \c"
\c
.MTO "inner\(atexample.org" "\fBInner" "\fB\c"
 \c
.URL "https://outer.example" "\fBtail" "\fB\c"
\fB \c
.URL "https://outer.example" "\fBafter" "\fB\c"
 end\fR\&.
.sp
L10 \fBBefore \c
.URL "https://example.org/note" "\fB\fBNote [1] Indexed\fB after" "\fB\c"
 end\fR\&. Reuse [1]\&.
.sp
L11 \fBBefore \c
.URL "https://one.example" "\fB\fBOne\fB" "\fB\c"
 and \c
.URL "https://two.example" "\fB\fBTwo\fB" "\fB\c"
 end\fR\&.
.sp
L12 \fBBefore \c
.URL "https://example.org/bracket" "\fB\fBBracket] text\fB after" "\fB\c"
 end\fR\&.
.sp
L13 \fBBefore https://escaped.example[*Literal* after] end\fR\&.
.sp
L14 \fBBefore \c
.URL "https://example.org/quoted" "\fB\fBQuoted\fB after" "\fB\c"
 end\fR\&.
.sp
L15 \fBBefore \c
.URL "https://example.org/attribute" "\fB*Expanded* after" "\fB\c"
 end\fR\&.
.sp
L16 \fI\c
.URL "https://example.org/edge" "\fI\fIEdge\fI" "\fI\c"
\fR\&.
.sp
L17 *Before \c
.URL "https://example.org/unclosed" "Unclosed* after" "\fR\c"
\&.
.sp
L18 \fBBefore \c
.URL "https://example.org/inner" "\fB*Unclosed after" "\fB\c"
 end\fR\&.
.sp
L19 \fBBefore \c
.URL "https://example.org/incomplete" "\fB" "\fB\c"
[Incomplete\fR after.
.sp
L20 \fBÉva \c
.URL "https://example.org/unicode" "\fB\fBcafé\fB after" "\fB\c"
 τέλος\fR\&.
.sp
L21 \fBBefore \c
.URL "https://example.org/escaped" "\fB*Literal* after" "\fB\c"
 end\fR\&.
.sp
L22 \fBBefore \c
.URL "https://example.org/multiline" "\fB\fBMultiline label\fB after" "\fB\c"
 end\fR\&.
.sp
L23 \fBBefore \c
.URL "https://example.org/query?pattern=*" "\fB\fBQuery\fB after" "\fB\c"
 end\fR\&.
.sp
L24 \fBBefore \c
.URL "https://example.org/role" "\fB\fBRole\fB after" "\fB\c"
 end\fR\&.
.sp
L25 \fBBefore \c
.URL "https://example.org/brackets" "\fBBefore [\fBnested\fB] after" "\fB\c"
 end\fR\&.
.sp
L26 \fBBefore \c
.URL "https://example.org/control" "\fBPlain" "\fB\c"
 end\fR\&.
.sp
L27 \c
.URL "https://example.org/control\-label" "\fBBold\fR after" "\fR\c"
\&.
.sp
L28 \fBFirst\fR \c
.URL "https://example.org/separate" "Label" "\fR\c"
 \fBSecond\fR\&.
.SH "TARGET"
.sp
Target text.
.SH "INDEX"
.SS "I"
.RS 4
Indexed
.br
.RE
.SH "NOTES"
.IP [1] 4
One note.
