'\" t
.\"     Title: passthrough-xrefs
.\"    Author: [see the "AUTHOR(S)" section]
.\" Generator: acdc 0.1.0
.\"      Date: 2026-07-31
.\"    Manual: \ \&
.\"    Source: \ \&
.\"  Language: English
.\"
.TH "PASSTHROUGH\-XREFS" "1" "2026-07-31" "\ \&" "\ \&"
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.ss \n[.ss] 0
.nh
.ad l
.de URL
\fI\\$2\fP <\\$1>\\$3
..
.als MTO URL
.if \n[.g] \{\
.  mso www.tmac
.  am URL
.    ad l
.  .
.  am MTO
.    ad l
.  .
.  LINKSTYLE blue R < >
.\}
.SH "NAME"
passthrough\-xrefs \- verify passthrough references
.SH "SYNOPSIS"
.sp
\fBpassthrough\-xrefs\fP
.SH "DESCRIPTION"
.sp
See Passthrough \fBTitle\fP, Custom Label, [untitled], [missing], and Explicit \fBText\fP\&.
titled-body
labeled-body
untitled-body
