'\" t
.\"     Title: callouts
.\"    Author: [see the "AUTHOR(S)" section]
.\" Generator: acdc 0.1.0
.\"      Date: 2026-09-29
.\"    Manual: Callout Tests
.\"    Source: acdc
.\"  Language: English
.\"
.TH "CALLOUTS" "1" "2026-09-29" "acdc" "Callout Tests"
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.ss \n[.ss] 0
.nh
.ad l
.de URL
\fI\\$2\fP <\\$1>\\$3
..
.als MTO URL
.if \n[.g] \{\
.  mso www.tmac
.  am URL
.    ad l
.  .
.  am MTO
.    ad l
.  .
.  LINKSTYLE blue R < >
.\}
.SH "NAME"
callouts \- test standalone callouts
.SH "DESCRIPTION"
.SS "Paragraph adjacent"
.sp
Prose.
<1> Alpha.
<2> Beta.
.SS "Paragraph blank"
.sp
Prose.
.RS 0
.IP \fB(1)\fP 4
Alpha.
.IP \fB(2)\fP 4
Beta.
.RE
.SS "Empty item"
.sp
<1>
<2> Beta.
.SS "Empty rest"
.RS 0
.IP \fB(1)\fP 4
Alpha.
<2>
.IP \fB(2)\fP 4
Gamma.
.RE
.SS "No space"
.sp
<1>Alpha.
<.>Beta.
<1>
.SS "Not markers"
.sp
\(<-1> Negative.
<+1> Plus.
<1.> Dot.
<..> Dots.
.SS "Escaped"
.sp
\e<1> Alpha.
\e<.> Beta.
.SS "Inline"
.sp
Inline <1> Alpha and <.> Beta.
.SS "Indented"
.sp
.if n .RS 4
.nf
.fam C
<1> Alpha.
<2> Beta.
.fam
.fi
.if n .RE
.SS "Indented after listing"
.EX
code \fB(1)\fP \fB(2)\fP
.EE
.sp
.if n .RS 4
.nf
.fam C
<1> Alpha.
<2> Beta.
.fam
.fi
.if n .RE
.SS "Tab indent"
.sp
 <1> Alpha.
<2> Beta.
.SS "Tab separator"
.RS 0
.IP \fB(1)\fP 4
Alpha.
.IP \fB(2)\fP 4
Beta.
.RE
.SS "Listing text"
.EX
<1> Alpha.
<2> Beta.
.EE
.SS "Literal style"
.sp
.if n .RS 4
.nf
.fam C
<1> Alpha.
<2> Beta.
.fam
.fi
.if n .RE
.SS "Source style"
.sp
.if n .RS 4
.nf
.fam C
<1> Alpha.
<2> Beta.
.fam
.fi
.if n .RE
.SS "Verse style"
.sp
.nf
<1> Alpha.
<2> Beta.
.fi
.SS "Compound literal"
.sp
Prose.
<1> Alpha.
.SS "Table asciidoc"
.TS
allbox tab(:);
ltx.
T{
.RS 0
.IP \fB(1)\fP 4
Alpha.
.IP \fB(2)\fP 4
Beta.
.RE

T}
.TE
.SS "Table normal"
.TS
allbox tab(:);
ltx.
T{
<1> Alpha.
<2> Beta.
T}
.TE
.SS "Blank-separated lists"
.RS 0
.IP \(bu 2
Parent bullet.
.RE
.RS 0
.IP \fB(1)\fP 4
Separate after bullet.
.RE
.RS 0
.IP 1. 4
Parent numbered item.
.RE
.RS 0
.IP \fB(1)\fP 4
Separate after numbered item.
.RE
.RS 0
.TP
\fBTerm\fP
Parent description.
.RE
.RS 0
.IP \fB(1)\fP 4
Separate after description.
.RE
