'\" t
.\"     Title: styled_paragraphs
.\"    Author: [see the "AUTHOR(S)" section]
.\" Generator: acdc 0.1.0
.\"      Date: 2025-12-08
.\"    Manual: Test Manual
.\"    Source: acdc
.\"  Language: English
.\"
.TH "STYLED_PARAGRAPHS" "1" "2025-12-08" "acdc" "Test Manual"
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.ss \n[.ss] 0
.nh
.ad l
.de URL
\fI\\$2\fP <\\$1>\\$3
..
.als MTO URL
.if \n[.g] \{\
.  mso www.tmac
.  am URL
.    ad l
.  .
.  am MTO
.    ad l
.  .
.  LINKSTYLE blue R < >
.\}
.SH "NAME"
styled_paragraphs \- test styled paragraph rendering
.SH "SYNOPSIS"
.sp
\fBstyled_paragraphs\fP [\fIOPTIONS\fP]
.SH "QUOTE STYLE"
.RS 3
.ll -.6i
.sp
Everything should be made as simple as possible, but not simpler.
.br
.RE
.ll
.RS 5
.ll -.10i
\(em Albert Einstein
.RE
.ll
.RS 3
.ll -.6i
.sp
Four score and seven years ago our fathers brought forth on this continent a new nation.
.br
.RE
.ll
.RS 5
.ll -.10i
Gettysburg Address \(em Abraham Lincoln
.RE
.ll
.SH "VERSE STYLE"
.sp
.nf
The fog comes
on little cat feet.
.fi
.br
.in +.5i
.ll -.5i
Fog \(em Carl Sandburg
.in
.ll
.SH "LITERAL STYLE"
.sp
.if n .RS 4
.nf
.fam C
This is literal text.
  It preserves   spacing.
.fam
.fi
.if n .RE
