'\" t
.\"     Title: prepared-code
.\"    Author: [see the "AUTHOR(S)" section]
.\" Generator: acdc 0.1.0
.\"      Date: 2026-10-02
.\"    Manual: \ \&
.\"    Source: \ \&
.\"  Language: English
.\"
.TH "PREPARED\-CODE" "1" "2026-10-02" "\ \&" "\ \&"
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.ss \n[.ss] 0
.nh
.ad l
.de URL
\fI\\$2\fP <\\$1>\\$3
..
.als MTO URL
.if \n[.g] \{\
.  mso www.tmac
.  am URL
.    ad l
.  .
.  am MTO
.    ad l
.  .
.  LINKSTYLE blue R < >
.\}
.SH "NAME"
prepared\-code \- formatted attributes in code
.SH "SYNOPSIS"
.sp
\fBprepared\-code\fR
.SH "DESCRIPTION"
.EX
Formatting: \fBBold\fR / \fBEarly\fR / \fBEarly\fR \(co / \c
.URL "https://example.org" "Site" "\fR\c"

Literal references: {bold} / {bold}
.EE
.EX
Escaped: \fBBold\fR / \fBEarly\fR / \fBEarly\fR \(co / \c
.URL "https://example.org" "Site" "\fR\c"
.EE
.EX
Macros: \fBBold\fR / [1] / [1] / Term
.EE
.EX
// Highlighted: \fBBold\fR / [1] / \c
.URL "https://example.org" "Site" "\fR\c"
 / Term
.EE
.SH "INDEX"
.SS "T"
.RS 4
Term
.br
.RE
.SH "NOTES"
.IP [1] 4
Note body.
