'\" t
.\"     Title: opening-contexts
.\"    Author: [see the "AUTHOR(S)" section]
.\" Generator: acdc 0.1.0
.\"      Date: 2026-10-03
.\"    Manual: Formatting boundaries
.\"    Source: acdc
.\"  Language: English
.\"
.TH "OPENING\-CONTEXTS" "1" "2026-10-03" "acdc" "Formatting boundaries"
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.ss \n[.ss] 0
.nh
.ad l
.de URL
\fI\\$2\fP <\\$1>\\$3
..
.als MTO URL
.if \n[.g] \{\
.  mso www.tmac
.  am URL
.    ad l
.  .
.  am MTO
.    ad l
.  .
.  LINKSTYLE blue R < >
.\}
.SH "NAME"
opening\-contexts \- constrained punctuation in substitution contexts
.SH "DESCRIPTION"
.sp
P01 <del>\fBbold \fIitalic\fB\fR</del>\&.
.sp
P02 <del>\fIitalic *bold*\fR</del>\&.
.sp
P03 <del>\f(CRCode\fR</del> <del>\fBMark\fR</del>\&.
.sp
P04 &\fBBold\fR <\fIItalic\fR >\f(CRCode\fR =\fBMark\fR\&.
.sp
P05 >\fBBold\fR <\fIItalic\fR &\f(CRCode\fR\&.
.sp
P06 >\fBBold\fR <\fIItalic\fR &\f(CRCode\fR\&.
.sp
P07 <del>\fBBold\fR</del> <del>*literal*</del>\&.
.sp
P08 =*literal* >_literal_ &`literal`.
.sp
P09 >\fBBold\fR <\fIItalic\fR &\f(CRCode\fR\&.
.sp
P10 >\fBBold\fR <\fIItalic\fR &\f(CRCode\fR\&.
.EX
P11 >\fBBold\fR =\fIItalic\fR &\f(CRCode\fR\&.
.EE
.sp
.if n .RS 4
.nf
.fam C
P12 >\fBBold\fR =\fIItalic\fR &\f(CRCode\fR\&.
.fam
.fi
.if n .RE
.RS 0
.IP \(bu 2
P13 =\fBBold\fR >\fIItalic\fR &\f(CRCode\fR\&.
.RE
.TS
allbox tab(:);
ltx.
T{
P14 =\fBBold\fR >\fIItalic\fR &\f(CRCode\fR\&.
T}
.TE
.sp
\fBP15 >\fBBold\fB =\fIItalic\fB &\f(CRCode\fB\&.\fR
.br
paragraph.
.SS "P16 >Bold =Italic &Code."
.sp
end.
