'\" t
.\"     Title: paragraph-subs
.\"    Author: [see the "AUTHOR(S)" section]
.\" Generator: acdc 0.1.0
.\"      Date: 2026-10-06
.\"    Manual: Parser checks
.\"    Source: acdc
.\"  Language: English
.\"
.TH "PARAGRAPH\-SUBS" "1" "2026-10-06" "acdc" "Parser checks"
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.ss \n[.ss] 0
.nh
.ad l
.de URL
\fI\\$2\fP <\\$1>\\$3
..
.als MTO URL
.if \n[.g] \{\
.  mso www.tmac
.  am URL
.    ad l
.  .
.  am MTO
.    ad l
.  .
.  LINKSTYLE blue R < >
.\}
.SH "NAME"
paragraph\-subs \- preserve substitutions in styled paragraphs
.SH "SYNOPSIS"
.sp
.if n .RS 4
.nf
.fam C
S01 code;; \fBbold\fR expanded \c
.URL "https://example.org" "link" "\fR\c"
 \fB(1)\fP
S02 next:: \fIitalic\fR \fB(2)\fP
.fam
.fi
.if n .RE
.RS 0
.IP \fB(1)\fP 4
Enabled substitutions in the source paragraph.
.IP \fB(2)\fP 4
Formatted continuation.
.RE
.sp
.if n .RS 4
.nf
.fam C
S03 literal;; <1>
S04 literal:: \e<2>
.fam
.fi
.if n .RE
.sp
.if n .RS 4
.nf
.fam C
S05 listing;; {value} *literal* <1>
.fam
.fi
.if n .RE
.sp
.if n .RS 4
.nf
.fam C
S06 inactive:: footnote:unused[No note.] indexterm2:[No entry] \fB(1)\fP
.fam
.fi
.if n .RE
.RS 0
.IP \fB(1)\fP 4
Default substitutions do not register these macros.
.RE
.sp
.if n .RS 4
.nf
.fam C
S07 active:: [1] \fB(1)\fP
.fam
.fi
.if n .RE
.RS 0
.IP \fB(1)\fP 4
The note is registered exactly once.
.RE
.sp
.nf
S08 verse;; {value} *literal*
.fi
.sp
Reuse [1]\&.
.SH "NOTES"
.IP [1] 4
One note.
