= Asciidoctor-diagram features

This document explains the various features of asciidoctor-diagram blocks using ditaa diagrams as an example.

== Simple diagrams

To mark a block as a diagram the appropriate style should be applied. This can be either `ditaa`, `graphviz` or `plantuml`.
These styles can be applied to literal, listing or open blocks.

A basic ditaa listing can be written as follows:

---------
[ditaa]
----
                   +-------------+
                   | asciidoctor |-------+
                   |  diagram    |       |
                   +-------------+       | png out
                       ^                 |
                       | ditaa in        |
                       |                 v
 +--------+   +--------+----+    /---------------\
 |        | --+ asciidoctor +--> |               |
 |  Text  |   +-------------+    |Beatiful output|
 |Document|   |   !magic!   |    |               |
 |     {d}|   |             |    |               |
 +---+----+   +-------------+    \---------------/
     :                                   ^
     |          Lots of work             |
     +-----------------------------------+
----
---------

results in the following image.

[ditaa]
----
                   +-------------+
                   | asciidoctor |-------+
                   |  diagram    |       |
                   +-------------+       | png out
                       ^                 |
                       | ditaa in        |
                       |                 v
 +--------+   +--------+----+    /---------------\
 |        | --+ asciidoctor +--> |               |
 |  Text  |   +-------------+    |Beatiful output|
 |Document|   |   !magic!   |    |               |
 |     {d}|   |             |    |               |
 +---+----+   +-------------+    \---------------/
     :                                   ^
     |          Lots of work             |
     +-----------------------------------+
----

== Controlling the file name

The image above gets the file name `58372f7d2ceffae9e91fd0a7cbb080b6.png`.
That long number is the checksum of the source code that was calculated by asciidoctor-diagram.
If you want to give your generated files a more meaningful name, simply fill in the `target` attribute.

This can be done by either specifying it as the first positional attribute or as a named attribute.
Both examples below would result in a file called `ditaa-diagram.png`.

---------
[ditaa, "ditaa-diagram"]
----
<snip>
----

[ditaa, target="ditaa-diagram"]
----
<snip>
----
---------

== Choosing an output format

By default images are generated in `PNG` format.
This can be overridden by defining the `format` (or 2nd positional) attribute.
The set of supported formats is diagram type dependent.
`ditaa` only supports the `png` format.
`graphviz` supports `png` and `svg`.
`plantuml` supports `png`, `svg` and `txt`.

The `txt` format is perhaps a bit non-obvious.
This generates an ascii art version of the UML diagrams.

The following Graphviz DOT script

---------
[graphviz, "dot_example", "svg"]
----
graph ethane {
     C_0 -- H_0 [type=s];
     C_0 -- H_1 [type=s];
     C_0 -- H_2 [type=s];
     C_0 -- C_1 [type=s];
     C_1 -- H_3 [type=s];
     C_1 -- H_4 [type=s];
     C_1 -- H_5 [type=s];
}
----
---------

generates an SVG representation of an ethane molecule footnote:[From http://en.wikipedia.org/wiki/DOT_(graph_description_language)#A_simple_example]

[graphviz, "dot_example", "svg"]
----
graph ethane {
     C_0 -- H_0 [type=s];
     C_0 -- H_1 [type=s];
     C_0 -- H_2 [type=s];
     C_0 -- C_1 [type=s];
     C_1 -- H_3 [type=s];
     C_1 -- H_4 [type=s];
     C_1 -- H_5 [type=s];
}
----

With https://github.com/Alwinator/graphviz-py[graphviz_py] you can also use variables and Python code to do calculations:

[graphviz_py, "graphviz_py_example", "svg"]
----
graph python_graph {
{{
import math

value = 0.5
sin = math.sin(value)
cos = math.cos(value)
}}

A [label="{{= value }}"];
B [label="{{= sin }}"];
C [label="{{= cos }}"];

A -- B [headlabel="sin"];
A -- C [headlabel="cos"];

}
----

Don't forget to install graphviz-py as described https://github.com/Alwinator/graphviz-py#installation[here].

== Using standard asciidoc features

Any remaining other attributes that are specified on a diagram block are copied over to the generated block.
This means you can use the regular http://asciidoctor.org/docs/user-manual/#put-images-in-their-place[asciidoc positioning attributes] to place the diagrams where you want to.

Block titles and block ids can also be applied in the same way to diagram blocks.

As an example, the following block

--------
[[plan]]
.My plan to conquer the world
[plantuml, align="center"]
--------

results in a block with the correct caption and id applied to it.

[[plan]]
.My plan to conquer the world
[plantuml, "activity_diagram", "svg", align="center"]
----
(*) --> "Create an Asciidoctor extension"
"Create an Asciidoctor extension" --> " ? "
" ? " --> "Profits!"
"Profits!" --> (*)
----

== Loading diagrams from external files

Asciidoctor-diagram also supports the various diagram block in block macro form.
These are macros of the form `<name>::<target>[<attrlist>]`.

In asciidoctor-diagram the macro names are identical to the block styles: `ditaa`, `graphviz` and `plantuml`
The target is the path to the file containing the diagram source code.
When the target is a relative path it is resolved with respect to the location of the document being processed.
The attribute list behaves mostly the same as with the block styles.
The only difference is that the `target` attribute is not supported.
Instead the name of the generated image is derived from the target propery of the macro.

The previous example in block macro form would look something like this with the text from the block located in a file called `activity_diagram.txt` instead of inline in the document.

----
plantuml::activity_diagram.txt[format="svg", align="center"]
----

== TikZ Diagram

[tikz, "circle-example", pdf, width=50%]
----
\begin{tikzpicture}
\draw (0,0) circle (1.5cm);
\node at (0,0) {Hello TikZ};
\end{tikzpicture}
----

== TikZ Diagram with a Preamble

[tikz, "preamble-example", pdf, preamble=true, width=50%]
----
\usetikzlibrary{shapes.multipart}
~~~~
\begin{tikzpicture}
\node [circle split, draw, fill=red!20] {
  Top \nodepart{lower} Bottom
};
\end{tikzpicture}
----

== TikZ Diagram using external fonts and lualatex

[tikz,,svg,float="center",align="center",preamble=true,command=lualatex]
----
\usepackage{fontspec}
\setmainfont[UprightFont={Petrona-Light.ttf},
             BoldFont={Petrona-Medium.ttf},
             ItalicFont={Petrona-LightItalic.ttf},
             BoldItalicFont={Petrona-MediumItalic.ttf},
            ]{Petrona-Light.ttf}
~~~~
\usetikzlibrary{calc,trees,matrix,positioning,chains,fit,intersections}
\usetikzlibrary{arrows,shapes.arrows,shapes.geometric,shapes.multipart,shapes.symbols}
\tikzset{
    state/.style={ rectangle, draw=black, thick, minimum height=1.66em, text centered, rounded corners=3pt},
    error state/.style={ rectangle, double, draw=black, semithick, minimum height=1.66em, text centered, rounded corners=3pt},
    off state/.style={ ellipse, double, draw=black, semithick, minimum height=1.66em, text centered, rounded corners=3pt},
    partial state/.style={trapezium, draw=black, thick, minimum height=1.66em, text centered, rounded corners=3pt},
    branch/.style={ fill, shape=circle, minimum size=3pt, inner sep=0pt},
    cross line/.style={preaction={draw=white, -, shorten >=3pt, shorten <=3pt, line width=2pt}},
    >=latex
}
\begin{tikzpicture}[scale=1.1]

  \node[off state,text width=2.5cm,minimum height=1.41cm,inner sep=0pt] at (-4.00,0)  (off) {\small\smash{Unconfigured} \hbox{\smash{(}Outermost Partial\smash{)}~}};

  \node[partial state,text width=1.1cm,inner sep=2pt] at (0,-0.35) (nested partial)  {\small Nested Partial};

  \node[error state, text width=1.3cm] at (0,-2)   (invalidated)    {Invalid\vphantom{g}};
  \node[error state] at (0,2)                      (various errors) {\scriptsize\begin{tabular}{@{}c@{}}Privilege Violation,\\Unsupported,\\Out of Memory\end{tabular}};
  \node[error state] at (0,3.5)                    (authfail)       {\footnotesize\begin{tabular}{@{}c@{}}Authentication\\Failed\end{tabular}};
  \node[error state, text width=1.3cm] at (0,-3.5) (expired)        {Expired};

  \node[coordinate] at ($(expired.east)+(0.5,0)$)  (before expired) {};

  \node[state, semithick, text width=1.1cm] at (3,0)      (ready)             {Ready\vphantom{g}};
  \node[state, semithick, text width=2.9cm] at (6.5,-1.5) (machine defined) {Machine-Defined};
  \node[state, semithick, text width=2.9cm] at (6.5,1.5)  (success failure)   {Success / Failure};
  \node[below right=0mm and -4mm of before expired]       (ignore)            {\small\textit{Expiration}};

  \draw[-,densely dashed]   (before expired) to[out=9,in=270,looseness=0.8] (ready);
  \draw[-,densely dashed]   (before expired) to[out=7,in=225,looseness=0.8] (machine defined);
  \draw[-,densely dashed]   (before expired) to[out=3,in=230,looseness=0.6] ($(success failure.south)+(-0.501,0)$);
  \draw[->,densely dashed]  ($(before expired)+(-0.1,0)$) -- (expired);

  \draw[<->,semithick,densely dotted] (off) -- (nested partial);

  %% Loop
  \draw[->,semithick,densely dotted] (nested partial) to[out=10,in=90] ($(nested partial.east)+(0.75,0)$) to[out=270,in=-10] (nested partial);

  \draw[<->,semithick,densely dotted] (off) to[out=82,in=180,looseness=0.8]  (authfail);
  \draw[<->,semithick,densely dotted] (off) to[out=55,in=180,looseness=0.7]  (various errors);
  \draw[<->,semithick,densely dotted] (off) to[out=-55,in=180,looseness=0.7] (invalidated);
  \draw[<->,semithick,densely dotted] (off) to[out=-82,in=180,looseness=0.8] (expired);

  %% Loop
  \draw[->] ($(machine defined.south)+(-0.125,0)$) to[out=258,in=180]
    ($(machine defined.south)+(0,-0.7)$) to[out=0,in=282] ($(machine defined.south)+(0.125,0)$);

  \draw[->,cross line] (machine defined) to[out=188,in=0,  looseness=1] ($(invalidated.east)+(0,-0.15)$);

  \draw[<->] ($(success failure.south)+(-1,0)$) to[out=225,in=10,looseness=0.8]   node[pos=0.34, above, sloped, yshift=-1pt] () {\tiny Conditional} ($(ready.east)!0.5!(ready.north east)$);

  \draw[<->,semithick,densely dotted] (off) to[out=8,in=167,looseness=0.8] (ready);
  \draw[<->,semithick,densely dotted, cross line] (off) to[out=-26,in=180,looseness=0.4] (machine defined);
  \draw[<->,semithick,densely dotted, cross line] (off) to[out=26,in=180,looseness=0.4] (success failure);

  \draw[->,cross line] ($(machine defined.north)+(-0.5,0)$) to[out=130,in=0,looseness=1] ($(various errors.east)+(0,0)$);

  \draw[->,cross line] ($(ready.south)+(-0.25,0)$) to[out=270,in=10,looseness=0.8] (invalidated);
  \draw[->,cross line] ($(ready.north)+(-0.25,0)$) to[out=90,in=-8,looseness=0.8] (various errors);


  \draw[<->,cross line] ($(machine defined.north)+(-1,0)$) to[out=135,in=-10,looseness=0.8] ($(ready.east)!0.5!(ready.south east)$);
  \draw[->,cross line] (machine defined) -- (success failure);

  \draw[->,cross line] (success failure) to[out=135,in=0,looseness=0.8] (authfail);
  \draw[->,cross line] ($(success failure.south)+(-0.75,0)$) to[out=230,in=0,looseness=1.2] (invalidated);

  \draw[->,cross line] (success failure) to[out=172,in=0, looseness=1] ($(various errors.east)+(0,0.15)$);

\end{tikzpicture}
----
