[package]
name = "acdc-backends-common"
version.workspace = true
edition.workspace = true
authors.workspace = true
description.workspace = true

[dependencies]
clap.workspace = true

[lints]
workspace = true
