# `acdc-cli`

This is the main binary for the command line processor. Think of it as the equivalent to
the `asciidoctor` tool.

## Usage

[source,console]
....
cargo run --all-features -- --help

A suite of tools for AsciiDoc documents

Usage: acdc-cli [OPTIONS] [FILES]...

Arguments:
  [FILES]...  List of files to parse

Options:
      --backend <BACKEND>      backend output format [default: html] [possible values: html, tck, terminal]
      --doctype <DOCTYPE>      document type to use when converting document [default: article] [possible values: article, book, manpage, inline]
      --safe-mode <SAFE_MODE>  safe mode to use when converting document [default: unsafe] [possible values: safe, unsafe, server, secure]
  -h, --help                   Print help
  -V, --version                Print version
....

## Backends supported

Check the `link:../backends/README.adoc[backends README]` for details on each of the
backends.

- `link:../backends/acdc-html[html]`
- `link:../backends/acdc-terminal[terminal]` (not built by default)
- `link:../backends/acdc-tck[tck]` (not built by default)

If you so wish, you can build an optional backend like so:

[source,console]
....
cargo build --features terminal
....

Alternatively, you can build them all like so:

[source,console]
....
cargo build --all-features
....