# `acdc-cli`

This is the main binary for the command line processor. Think of it as the equivalent to
the `asciidoctor` tool.

## Usage

[source,console]
....
cargo run --all-features -- --help

A suite of tools for AsciiDoc documents

Usage: acdc-cli [OPTIONS] [FILES]...

Arguments:
  [FILES]...  List of files to parse

Options:
      --backend <BACKEND>      backend output format [default: html] [possible values: html, tck, terminal]
      --doctype <DOCTYPE>      document type to use when converting document [default: article] [possible values: article, book, manpage, inline]
      --safe-mode <SAFE_MODE>  safe mode to use when converting document [default: unsafe] [possible values: safe, unsafe, server, secure]
  -h, --help                   Print help
  -V, --version                Print version
....

## Backends (converters) supported

Check the `link:../converters/README.adoc[converters README]` for details.

- `link:../converters/html[html]`
- `link:../converters/terminal[terminal]` (not built by default)
- `link:../converters/tck[tck]` (not built by default)

### Building an optional backend

[source,console]
....
cargo build --features terminal
....

Alternatively, you can build them all like so:

[source,console]
....
cargo build --all-features
....

## Extra Logging

If you want more logs, especially useful if you're troubleshooting or reporting an error,
please adjust the `ACDC_LOG` environment variable.

[source,console]
....
ACDC_LOG=trace cargo run <your file>
....

or if you're running a binary already built:

[source,console]
....
ACDC_LOG=trace acdc <your file>
....
