//! Syntax highlighting for source code blocks using syntect.
//!
//! This module provides syntax highlighting for code blocks when the
//! `highlighting` feature is enabled. It supports two output modes:
//!
//! - **Inline** (default): `<span style="color:#...">` — themes baked into HTML
//! - **Class**: `<span class="syntax-keyword">` — themes applied via CSS classes
//!
//! The mode is controlled by `:highlight-css:`. `syntect-css` is a
//! `[deprecated]` compatibility alias.
//!
//! # Callout Handling
//!
//! Code blocks may contain callout references (e.g., `<1>`, `<2>`) that need
//! to be rendered as HTML elements, not as part of the highlighted code.
//! We track callout positions during text extraction and inject the proper
//! HTML (`<i class="conum" data-value="N"></i><b>(N)</b>`) after highlighting.

#[cfg(feature = "highlighting")]
use std::{
    fmt::Write as _,
    io::{Error as IoError, Write},
};
#[cfg(feature = "highlighting")]
use syntect::parsing::SyntaxSet;

#[cfg(feature = "highlighting")]
use acdc_converters_core::{
    Diagnostics, InlineTextTransform,
    code::{SourceLineOptions, source_line_count},
    substitutions::TextBoundaries,
};
#[cfg(feature = "highlighting")]
use acdc_parser::{BlockMetadata, InlineNode};

#[cfg(feature = "highlighting")]
use crate::Error;

/// Default light theme.
#[cfg(feature = "highlighting")]
pub(crate) const DEFAULT_THEME_LIGHT: &str = "InspiredGitHub";
/// Default dark theme.
#[cfg(feature = "highlighting")]
pub(crate) const DEFAULT_THEME_DARK: &str = "base16-eighties.dark";

/// How syntax-highlighted spans are styled in the HTML output.
#[cfg(feature = "highlighting")]
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default)]
pub(crate) enum HighlightMode {
    /// Inline `style="color:…"` attributes (default, backward-compatible).
    #[default]
    Inline,
    /// CSS class names (`class="syntax-keyword"`) — requires a `<style>` block
    /// generated by [`highlight_css`].
    Class,
}

#[cfg(feature = "highlighting")]
#[derive(Clone, Copy)]
pub(crate) struct HighlightOptions<'a> {
    pub(crate) language: &'a str,
    pub(crate) theme_name: &'a str,
    pub(crate) mode: HighlightMode,
    pub(crate) text_context: Option<&'a [InlineNode<'a>]>,
}

/// The `ClassStyle` used for class-based output.  Every scope token is
/// prefixed with `syntax-` so the generated classes don't collide with
/// the rest of the page's styles.
#[cfg(feature = "highlighting")]
const SYNTAX_CLASS_STYLE: syntect::html::ClassStyle =
    syntect::html::ClassStyle::SpacedPrefixed { prefix: "syntax-" };

/// Highlight code, apply source-line decoration, and write HTML output.
///
/// Callout references are preserved and rendered as proper HTML elements
/// at their displayed byte offsets, including multiple references on one line.
#[cfg(feature = "highlighting")]
pub(crate) fn highlight_code<W: Write + ?Sized>(
    writer: &mut W,
    inlines: &[InlineNode],
    metadata: &BlockMetadata<'_>,
    options: HighlightOptions<'_>,
    links: &[HighlightedLink],
    replacements: bool,
    diagnostics: Option<&mut Diagnostics<'_>>,
) -> Result<(), Error> {
    let HighlightOptions {
        language,
        theme_name,
        mode,
        text_context,
    } = options;
    let (code, callouts) = extract_text_and_callouts(
        inlines,
        replacements,
        TextBoundaries::BOTH,
        text_context,
        diagnostics,
    );
    let syntax_set = SyntaxSet::load_defaults_newlines();

    let syntax = syntax_set
        .find_syntax_by_token(language)
        .or_else(|| syntax_set.find_syntax_by_extension(language))
        .unwrap_or_else(|| syntax_set.find_syntax_plain_text());

    let options = SourceLineOptions::resolve(metadata, &code);
    if options.is_empty() && links.is_empty() && callouts.is_empty() {
        return match mode {
            HighlightMode::Inline => {
                highlight_code_inline(writer, &code, &syntax_set, syntax, theme_name)
            }
            HighlightMode::Class => highlight_code_classed(writer, &code, &syntax_set, syntax),
        };
    }

    let mut highlighted = Vec::new();
    match mode {
        HighlightMode::Inline => {
            highlight_code_inline(&mut highlighted, &code, &syntax_set, syntax, theme_name)
        }
        HighlightMode::Class => {
            highlight_code_classed(&mut highlighted, &code, &syntax_set, syntax)
        }
    }?;

    let highlighted = String::from_utf8_lossy(&highlighted);
    let callouts = callouts
        .into_iter()
        .map(|(offset, number)| HighlightedLink {
            range: offset..offset + 1,
            html: format!("<i class=\"conum\" data-value=\"{number}\"></i><b>({number})</b>"),
            outside_spans: true,
        })
        .collect::<Vec<_>>();
    // Insert every fragment against the same text offsets: a rendered link or
    // callout must not shift the offsets of the fragments that follow it.
    let mut fragments = links.iter().chain(&callouts).collect::<Vec<_>>();
    fragments.sort_by_key(|fragment| fragment.range.start);
    let linked = insert_highlighted_links(&highlighted, &fragments);
    if options.is_empty() {
        writer.write_all(linked.as_bytes())?;
        return Ok(());
    }
    let highlighted = close_spans_at_line_boundaries(&linked);
    let decorated = decorate_source_lines(&highlighted, &code, &options, theme_name);
    writer.write_all(decorated.as_bytes())?;
    Ok(())
}

#[cfg(feature = "highlighting")]
fn close_spans_at_line_boundaries(html: &str) -> String {
    // Reopen syntax spans and linked labels inside each source-line wrapper.
    let mut output = String::with_capacity(html.len());
    let mut open_tags: Vec<String> = Vec::new();
    let mut remaining = html;
    while !remaining.is_empty() {
        if remaining.starts_with('<')
            && let Some(end) = remaining.find('>')
        {
            let (tag, rest) = remaining.split_at(end + 1);
            output.push_str(tag);
            let name = tag
                .trim_start_matches('<')
                .split([' ', '>'])
                .next()
                .unwrap_or_default();
            if name.starts_with('/') {
                open_tags.pop();
            } else if !matches!(name, "br" | "img" | "wbr") {
                open_tags.push(tag.to_owned());
            }
            remaining = rest;
        } else if let Some(rest) = remaining.strip_prefix('\n') {
            for tag in open_tags.iter().rev() {
                let name = tag
                    .trim_start_matches('<')
                    .split([' ', '>'])
                    .next()
                    .unwrap_or_default();
                output.push_str("</");
                output.push_str(name);
                output.push('>');
            }
            output.push('\n');
            for tag in &mut open_tags {
                // Repeated fragments share the destination, but not an explicit ID.
                if let Some(start) = tag.find(" id=\"")
                    && let Some(rest) = tag.get(start + 5..)
                    && let Some(end) = rest.find('"')
                {
                    tag.replace_range(start..start + 6 + end, "");
                }
                output.push_str(tag);
            }
            remaining = rest;
        } else {
            let Some(character) = remaining.chars().next() else {
                break;
            };
            output.push(character);
            remaining = &remaining[character.len_utf8()..];
        }
    }
    output
}

#[cfg(feature = "highlighting")]
fn decorate_source_lines(
    html: &str,
    source: &str,
    options: &SourceLineOptions,
    theme_name: &str,
) -> String {
    if options.is_empty() {
        return html.to_owned();
    }

    let highlight_colour = source_highlight_colour(theme_name);
    let mut decorated = String::with_capacity(html.len() + options.highlighted_lines.len() * 96);
    for (index, line) in html.split_inclusive('\n').enumerate() {
        if options
            .highlighted_lines
            .binary_search(&(index + 1))
            .is_ok()
        {
            let _ = write!(
                decorated,
                "<span class=\"hll\" style=\"display:block;background-color:{highlight_colour}\">{line}</span>"
            );
        } else {
            decorated.push_str(line);
        }
    }

    let Some(start) = options.line_number_start else {
        return decorated;
    };
    let line_count = source_line_count(source);
    let mut numbers = String::new();
    for offset in 0..line_count {
        if offset > 0 {
            numbers.push('\n');
        }
        let _ = write!(numbers, "{}", start.saturating_add(offset));
    }
    format!(
        "<table class=\"linenotable\"><tbody><tr><td class=\"linenos\"><pre class=\"lineno\">{numbers}</pre></td><td class=\"code\"><pre>{decorated}</pre></td></tr></tbody></table>"
    )
}

#[cfg(feature = "highlighting")]
fn source_highlight_colour(theme_name: &str) -> String {
    use syntect::highlighting::{Color, ThemeSet};

    let colour = ThemeSet::load_defaults()
        .themes
        .get(theme_name)
        .and_then(|theme| theme.settings.line_highlight)
        .unwrap_or(Color {
            r: 255,
            g: 255,
            b: 204,
            a: 255,
        });
    format!(
        "rgba({},{},{},{:.3})",
        colour.r,
        colour.g,
        colour.b,
        f64::from(colour.a) / 255.0
    )
}

/// Inline-style highlighting (existing behaviour).
#[cfg(feature = "highlighting")]
fn highlight_code_inline<W: Write + ?Sized>(
    writer: &mut W,
    code: &str,
    syntax_set: &SyntaxSet,
    syntax: &syntect::parsing::SyntaxReference,
    theme_name: &str,
) -> Result<(), Error> {
    use syntect::{highlighting::ThemeSet, html::highlighted_html_for_string};

    let theme_set = ThemeSet::load_defaults();
    let Some(theme) = theme_set.themes.get(theme_name) else {
        return Ok(writer.write_all(html_escape(code).as_bytes())?);
    };

    let html = highlighted_html_for_string(code, syntax_set, syntax, theme)
        .map_err(|e| Error::Io(IoError::other(e)))?;

    // syntect wraps output in <pre style="..."> which we don't want
    // since we already have our own <pre> wrapper. Extract just the inner content.
    let content = extract_inner_content(&html);

    write!(writer, "{content}")?;

    Ok(())
}

/// Class-based highlighting using `ClassedHTMLGenerator`.
#[cfg(feature = "highlighting")]
fn highlight_code_classed<W: Write + ?Sized>(
    writer: &mut W,
    code: &str,
    syntax_set: &SyntaxSet,
    syntax: &syntect::parsing::SyntaxReference,
) -> Result<(), Error> {
    use syntect::html::ClassedHTMLGenerator;

    let mut generator =
        ClassedHTMLGenerator::new_with_class_style(syntax, syntax_set, SYNTAX_CLASS_STYLE);
    for line in syntect::util::LinesWithEndings::from(code) {
        generator
            .parse_html_for_line_which_includes_newline(line)
            .map_err(|e| Error::Io(IoError::other(e)))?;
    }
    let html = generator.finalize();

    write!(writer, "{html}")?;

    Ok(())
}

/// Generate a CSS stylesheet for class-based syntax highlighting.
///
/// Returns the CSS rules that map `.syntax-*` classes to the colours of
/// the given theme. Embed this in a `<style>` block in the `<head>`.
#[cfg(feature = "highlighting")]
pub(crate) fn highlight_css(theme_name: &str) -> Result<String, Error> {
    use syntect::{highlighting::ThemeSet, html::css_for_theme_with_class_style};

    let theme_set = ThemeSet::load_defaults();
    let theme = theme_set.themes.get(theme_name).ok_or_else(|| {
        Error::Io(IoError::other(format!(
            "unknown syntect theme: {theme_name}"
        )))
    })?;

    css_for_theme_with_class_style(theme, SYNTAX_CLASS_STYLE)
        .map_err(|e| Error::Io(IoError::other(e)))
}

/// Extract the inner content from syntect's inline-style HTML output.
/// Syntect wraps everything in `<pre style="...">...</pre>`, but we want just the spans.
/// It also emits a leading newline after the opening tag which we strip to avoid
/// extra whitespace at the top of the code block.
#[cfg(feature = "highlighting")]
fn extract_inner_content(html: &str) -> &str {
    let start = html.find('>').map_or(0, |i| i + 1);
    let end = html.rfind("</pre>").unwrap_or(html.len());
    let content = html.get(start..end).unwrap_or(html);
    content.strip_prefix('\n').unwrap_or(content)
}

/// HTML-escape special characters.
#[cfg(feature = "highlighting")]
fn html_escape(s: &str) -> String {
    s.replace('&', "&amp;")
        .replace('<', "&lt;")
        .replace('>', "&gt;")
        .replace('"', "&quot;")
}

/// Extract text content and callout positions from inline nodes for highlighting.
///
/// Returns the code text with a space standing in for each callout, plus the
/// placeholders' byte offsets and callout numbers in source order.
/// Ordinary fragments and captured labels must already contain display text.
/// Visible index labels retain their profiles and use `replacements` for
/// ordinary label text.
#[cfg(feature = "highlighting")]
pub(crate) fn extract_text_and_callouts(
    inlines: &[InlineNode],
    replacements: bool,
    boundaries: TextBoundaries,
    text_context: Option<&[InlineNode]>,
    mut diagnostics: Option<&mut Diagnostics<'_>>,
) -> (String, Vec<(usize, usize)>) {
    let mut result = String::new();
    let mut callouts = Vec::new();
    let text_context = text_context.unwrap_or(inlines);

    for (index, node) in inlines.iter().enumerate() {
        #[allow(clippy::match_same_arms)]
        match node {
            InlineNode::VerbatimText(verbatim) => {
                result.push_str(verbatim.content);
            }
            InlineNode::RawText(raw) => {
                result.push_str(raw.content);
            }
            InlineNode::PlainText(plain) => {
                result.push_str(plain.content);
            }
            InlineNode::LineBreak(_) => {
                result.push('\n');
            }
            InlineNode::CalloutRef(callout) => {
                callouts.push((result.len(), callout.number));
                // Marker-only lines still need a line number/highlight. Replacing
                // this space with the marker adds no rendered whitespace.
                result.push(' ');
            }
            InlineNode::Macro(acdc_parser::InlineMacro::IndexTerm(term)) => {
                if term.is_visible() {
                    // Index labels remain structured until text extraction, so
                    // apply their display substitutions here. Catalog labels
                    // are registered independently from the original nodes.
                    let text = InlineTextTransform::default()
                        .line_break("\n")
                        .decode_char_refs(true)
                        .rendered_replacements(replacements)
                        .text_boundaries(
                            boundaries
                                .with_ordinary_replacements(replacements)
                                .for_inline(text_context, index),
                        )
                        .to_string(std::slice::from_ref(node));
                    result.push_str(&text);
                }
            }
            InlineNode::BoldText(_)
            | InlineNode::ItalicText(_)
            | InlineNode::MonospaceText(_)
            | InlineNode::HighlightText(_)
            | InlineNode::SubscriptText(_)
            | InlineNode::SuperscriptText(_)
            | InlineNode::CurvedQuotationText(_)
            | InlineNode::CurvedApostropheText(_)
            | InlineNode::StandaloneCurvedApostrophe(_)
            | InlineNode::InlineAnchor(_)
            | InlineNode::Macro(_) => {}
            node => {
                if let Some(diagnostics) = diagnostics.as_deref_mut() {
                    diagnostics.warn_with_advice(
                        format!(
                            "unsupported inline node in highlighted code, skipping node: {node:?}"
                        ),
                        "Use plain source output for this block and report the unsupported construct.",
                    );
                }
            }
        }
    }
    (result, callouts)
}

#[cfg(all(test, feature = "highlighting"))]
mod tests {
    use super::*;
    use acdc_parser::{CalloutRef, CalloutRefKind, Location, Verbatim};

    fn create_verbatim_inlines(content: &str) -> Vec<InlineNode<'_>> {
        vec![InlineNode::VerbatimText(Verbatim {
            content,
            location: Location::default(),
        })]
    }

    fn create_callout_ref(number: usize) -> InlineNode<'static> {
        InlineNode::CalloutRef(CalloutRef {
            kind: CalloutRefKind::Explicit,
            number,
            location: Location::default(),
        })
    }

    #[test]
    fn test_extract_text_and_callouts_from_verbatim() {
        let inlines = create_verbatim_inlines("fn main() {\n    println!(\"Hello\");\n}");
        let (text, callouts) =
            extract_text_and_callouts(&inlines, false, TextBoundaries::BOTH, None, None);
        assert_eq!(text, "fn main() {\n    println!(\"Hello\");\n}");
        assert!(callouts.is_empty());
    }

    #[test]
    fn test_extract_text_and_callouts_with_callouts() {
        let inlines = vec![
            InlineNode::VerbatimText(Verbatim {
                content: "let x = 1; ",
                location: Location::default(),
            }),
            create_callout_ref(1),
            InlineNode::VerbatimText(Verbatim {
                content: "\nlet y = 2; ",
                location: Location::default(),
            }),
            create_callout_ref(2),
            InlineNode::VerbatimText(Verbatim {
                content: "\n",
                location: Location::default(),
            }),
        ];

        let (text, callouts) =
            extract_text_and_callouts(&inlines, false, TextBoundaries::BOTH, None, None);
        assert_eq!(text, "let x = 1;  \nlet y = 2;  \n");
        assert_eq!(callouts, [(11, 1), (24, 2)]);
    }

    #[test]
    #[allow(clippy::expect_used)]
    fn test_highlight_code_with_callouts() -> Result<(), Error> {
        let inlines = vec![
            InlineNode::VerbatimText(Verbatim {
                content: "let x = 1; ",
                location: Location::default(),
            }),
            create_callout_ref(1),
            InlineNode::VerbatimText(Verbatim {
                content: "\nlet y = 2; ",
                location: Location::default(),
            }),
            create_callout_ref(2),
        ];

        let mut buffer = Vec::new();
        highlight_code(
            &mut buffer,
            &inlines,
            &BlockMetadata::new(),
            HighlightOptions {
                language: "rust",
                theme_name: DEFAULT_THEME_LIGHT,
                mode: HighlightMode::Inline,
                text_context: None,
            },
            &[],
            false,
            None,
        )?;

        let html = String::from_utf8(buffer).expect("valid utf8");
        assert!(
            html.contains("<i class=\"conum\" data-value=\"1\"></i><b>(1)</b>"),
            "Should contain callout 1 HTML, got: {html}"
        );
        assert!(
            html.contains("<i class=\"conum\" data-value=\"2\"></i><b>(2)</b>"),
            "Should contain callout 2 HTML, got: {html}"
        );
        assert!(
            !html.contains("&lt;1&gt;"),
            "Callouts should not appear as escaped text: {html}"
        );

        Ok(())
    }

    #[test]
    #[allow(clippy::expect_used)]
    fn test_highlight_rust_code() -> Result<(), Error> {
        let code = "fn main() {\n    println!(\"Hello, world!\");\n}";
        let inlines = create_verbatim_inlines(code);

        let mut buffer = Vec::new();
        highlight_code(
            &mut buffer,
            &inlines,
            &BlockMetadata::new(),
            HighlightOptions {
                language: "rust",
                theme_name: DEFAULT_THEME_LIGHT,
                mode: HighlightMode::Inline,
                text_context: None,
            },
            &[],
            false,
            None,
        )?;

        let html = String::from_utf8(buffer).expect("valid utf8");
        assert!(
            html.contains("<span"),
            "Should produce highlighted output with spans"
        );

        Ok(())
    }

    #[test]
    #[allow(clippy::expect_used)]
    fn test_highlight_unknown_language_fallback() -> Result<(), Error> {
        let code = "some code here";
        let inlines = create_verbatim_inlines(code);

        let mut buffer = Vec::new();
        highlight_code(
            &mut buffer,
            &inlines,
            &BlockMetadata::new(),
            HighlightOptions {
                language: "unknown_lang_xyz",
                theme_name: DEFAULT_THEME_LIGHT,
                mode: HighlightMode::Inline,
                text_context: None,
            },
            &[],
            false,
            None,
        )?;

        assert!(
            !buffer.is_empty(),
            "Should produce output even with unknown language"
        );
        assert_eq!(
            std::str::from_utf8(&buffer).expect("valid utf8"),
            "<span style=\"color:#323232;\">some code here</span>"
        );
        Ok(())
    }

    #[test]
    #[allow(clippy::expect_used)]
    fn test_highlight_class_mode_produces_class_spans() -> Result<(), Error> {
        let code = "fn main() {}";
        let inlines = create_verbatim_inlines(code);

        let mut buffer = Vec::new();
        highlight_code(
            &mut buffer,
            &inlines,
            &BlockMetadata::new(),
            HighlightOptions {
                language: "rust",
                theme_name: DEFAULT_THEME_LIGHT,
                mode: HighlightMode::Class,
                text_context: None,
            },
            &[],
            false,
            None,
        )?;

        let html = String::from_utf8(buffer).expect("valid utf8");
        assert!(
            html.contains("class=\"syntax-"),
            "Class mode should produce class= spans, got: {html}"
        );
        assert!(
            !html.contains("style="),
            "Class mode should not produce style= attributes, got: {html}"
        );
        Ok(())
    }

    #[test]
    #[allow(clippy::expect_used)]
    fn test_highlight_class_mode_with_callouts() -> Result<(), Error> {
        let inlines = vec![
            InlineNode::VerbatimText(Verbatim {
                content: "let x = 1; ",
                location: Location::default(),
            }),
            create_callout_ref(1),
            InlineNode::VerbatimText(Verbatim {
                content: "\nlet y = 2; ",
                location: Location::default(),
            }),
            create_callout_ref(2),
        ];

        let mut buffer = Vec::new();
        highlight_code(
            &mut buffer,
            &inlines,
            &BlockMetadata::new(),
            HighlightOptions {
                language: "rust",
                theme_name: DEFAULT_THEME_LIGHT,
                mode: HighlightMode::Class,
                text_context: None,
            },
            &[],
            false,
            None,
        )?;

        let html = String::from_utf8(buffer).expect("valid utf8");
        assert!(
            html.contains("<i class=\"conum\" data-value=\"1\"></i><b>(1)</b>"),
            "Class mode should preserve callouts, got: {html}"
        );
        assert!(
            html.contains("<i class=\"conum\" data-value=\"2\"></i><b>(2)</b>"),
            "Class mode should preserve callouts, got: {html}"
        );
        Ok(())
    }

    #[test]
    fn test_highlight_css_generates_stylesheet() -> Result<(), Error> {
        let css = highlight_css(DEFAULT_THEME_LIGHT)?;
        assert!(
            css.contains(".syntax-"),
            "CSS should contain .syntax- prefixed rules, got: {css}"
        );
        assert!(css.contains("color:"), "CSS should contain color rules");
        Ok(())
    }

    #[test]
    fn test_highlight_css_custom_theme() -> Result<(), Error> {
        let css = highlight_css("base16-ocean.dark")?;
        assert!(css.contains(".syntax-"));
        Ok(())
    }

    #[test]
    fn test_highlight_css_unknown_theme_errors() {
        let result = highlight_css("nonexistent-theme");
        assert!(result.is_err());
    }

    #[test]
    fn decorates_highlighted_lines_and_custom_line_numbers() {
        let options = SourceLineOptions {
            line_number_start: Some(10),
            highlighted_lines: vec![2],
        };
        let html = decorate_source_lines(
            "<span>one</span>\n<span>two</span>\n<span>three</span>",
            "one\ntwo\nthree",
            &options,
            DEFAULT_THEME_LIGHT,
        );

        assert!(html.contains("<pre class=\"lineno\">10\n11\n12</pre>"));
        assert!(html.contains("class=\"hll\""));
        assert!(html.contains("><span>two</span>\n</span>"));
    }

    #[test]
    fn closes_and_reopens_highlight_spans_at_line_boundaries() {
        assert_eq!(
            close_spans_at_line_boundaries("<span class=\"syntax\">one\ntwo</span>"),
            "<span class=\"syntax\">one</span>\n<span class=\"syntax\">two</span>"
        );
    }
}

#[cfg(feature = "highlighting")]
pub(crate) struct HighlightedLink {
    pub(crate) range: std::ops::Range<usize>,
    pub(crate) html: String,
    pub(crate) outside_spans: bool,
}

#[cfg(feature = "highlighting")]
impl HighlightedLink {
    fn append_html(&self, output: &mut String, spans: &[&str]) {
        // Raw tags can cross highlight runs; callouts must not inherit token
        // colors. Close and reopen syntax spans around these fragments.
        if self.outside_spans {
            for _ in spans {
                output.push_str("</span>");
            }
        }
        output.push_str(&self.html);
        if self.outside_spans {
            for span in spans {
                output.push_str(span);
            }
        }
    }
}

#[cfg(feature = "highlighting")]
fn insert_highlighted_links(html: &str, links: &[&HighlightedLink]) -> String {
    if links.is_empty() {
        return html.to_owned();
    }
    let mut output = String::with_capacity(html.len());
    let mut remaining = html;
    let mut offset = 0;
    let mut links = links.iter().peekable();
    let mut spans = Vec::new();
    while !remaining.is_empty() {
        if remaining.starts_with('<')
            && let Some(end) = remaining.find('>')
        {
            let (tag, rest) = remaining.split_at(end + 1);
            if tag.starts_with("<span ") || tag == "<span>" {
                spans.push(tag);
            } else if tag == "</span>" {
                spans.pop();
            }
            output.push_str(tag);
            remaining = rest;
            continue;
        }
        while links.peek().is_some_and(|link| link.range.end <= offset) {
            if let Some(link) = links.next()
                && link.range.is_empty()
                && link.range.start == offset
            {
                link.append_html(&mut output, &spans);
            }
        }
        let link = links.peek();
        if let Some(link) = link
            && link.range.start == offset
        {
            link.append_html(&mut output, &spans);
        }
        let Some(character) = remaining.chars().next() else {
            break;
        };
        let (length, decoded_length) = if character == '&'
            && let Some(end) = remaining.find(';')
            && let Some(entity) = remaining.get(..=end)
            && let Some(decoded) = decoded_entity(entity)
        {
            (end + 1, decoded.len_utf8())
        } else {
            (character.len_utf8(), character.len_utf8())
        };
        let (text, rest) = remaining.split_at(length);
        if link.is_none_or(|link| offset < link.range.start) {
            output.push_str(text);
        }
        offset += decoded_length;
        remaining = rest;
    }
    for link in links {
        if link.range.is_empty() && link.range.start == offset {
            link.append_html(&mut output, &spans);
        }
    }
    output
}

#[cfg(feature = "highlighting")]
fn decoded_entity(entity: &str) -> Option<char> {
    match entity {
        "&amp;" => Some('&'),
        "&lt;" => Some('<'),
        "&gt;" => Some('>'),
        "&quot;" => Some('"'),
        "&apos;" => Some('\''),
        _ => {
            let number = entity.strip_prefix("&#")?.strip_suffix(';')?;
            let value = if let Some(hex) = number.strip_prefix('x') {
                u32::from_str_radix(hex, 16).ok()?
            } else {
                number.parse().ok()?
            };
            char::from_u32(value)
        }
    }
}
