= My document
:date: 2025-01-15T10:00:00+00:00
:description: A quick preview
:toc: macro
:icons: font
:stem: asciimath

toc::[]

icon:arrow-right[]
This is a *live preview* editor for https://asciidoc.org[AsciiDoc].

== Getting started

Type in the left pane and see the rendered output on the right.

This is using icon:github[set=brands] https://github.com/nlopes/acdc/tree/main/acdc-parser[`acdc-parser`], which you can find in the icon:github[set=brands] https://github.com/nlopes/acdc[`acdc`] repository.

* Unordered list item
* Another item

=== Media

.A random video
video::RvRhUHTV_8k[youtube,list=PLDitloyBcHOm49bxNhvGgg0f9NRZ5lSaP]

=== Stem

A matrix can be written as stem:[[[a,b\],[c,d\]\]((n),(k))].

And another inline formula: latexmath:[C = \alpha + \beta Y^{\gamma} + \epsilon].

[stem]
++++
sqrt(4) = 2
++++

=== Code blocks footnote:code-blocks[I love code blocks]

."Hello World" example
[%collapsible%open]
====
[source,rust]
----
fn main() {
    println!("Hello from the editor!");
}
----
====

=== Tables
.List of night agents
[%header,cols="30%,"]
|===
|Name|Email
|Peter Sutherland|peter.sutherland@example.com
|Adam Corrigan|adam.corrigan@example.com
|===

TIP: Try adding sections, lists, and inline formatting.
