.sp
\c
.URL "https://example.org" "One \(dqquote\(dq two" "\c"

.sp
\c
.URL "https://example.org" "Expanded \(dqquote\(dq" "\c"

.sp
\c
.URL "https://example.org" "Expanded \(dqquote\(dq" "\c"

.sp
\c
.URL "https://example.org" "\fBBold \(dqquote\(dq label\fP" "\c"

.EX
\c
.URL "https://example.org" "One \(dqquote\(dq two" "\c"

\c
.URL "https://example.net" "One \(dqquote\(dq two" "\c"

\c
.MTO "test\(atexample.org" "One \(dqquote\(dq two" "\c"
.EE
.sp
\c
.URL "https://example.org" "One \(dqquote\(dq ] two" "\c"

.sp
link:https://example.org["One \e"quote\e" two",role=green]
.EX
link:https://example.org["One \e"quote\e" two",role=green]
.EE
.sp
\c
.URL "https://example.org" "Label One \(dqquote\(dq [1] tail" "\c"

.sp
Reuse [1]\&.
.sp
\c
.URL "https://example.org" "One \(dqquote\(dq" "\c"

.sp
\c
.URL "https://example.org" "One \e\(dqquote\e\(dq" "\c"

.sp
\c
.URL "https://example.org" "One" "\c"

.sp
\c
.URL "https://example.org" "\(dqOne\(dq" "\c"

.sp
\c
.URL "https://example.org" "a=b" "\c"

.sp
\c
.URL "https://example.org" "\(dqa=b\(dq" "\c"

.SH "INDEX"
.SS "O"
.RS 4
One \e"quote\e"
.br
.RE
