.SH "DESCRIPTION"
.sp
Default: CHAPTER \fBBOLD\fR; UNNUMBERED CHAPTER; APPENDIX\&.
.sp
Basic: CHAPTER \fBBOLD\fR; UNNUMBERED CHAPTER; \fIAppendix\fR\&.
.sp
Short: Section 3; UNNUMBERED CHAPTER; Appendix A\&.
.sp
Full: Section 3, \(lqChapter \fBbold\fR\(rq; UNNUMBERED CHAPTER; Appendix A, \fIAppendix\fR\&.
.sp
Fallback: CHAPTER \fBBOLD\fR; CHAPTER \fBBOLD\fR\&.
.sp
Explicit: Custom \fBlabel\fR; Reference \fBlabel\fR\&.
.sp
Document basic: CHAPTER \fBBOLD\fR; UNNUMBERED CHAPTER; \fIAppendix\fR; Ordinary section; Reference \fBlabel\fR\&.
.sp
Document note.[1]
.sp
Script: ^(CHAPTER \fBBOLD\fR)\&.
.TS
allbox tab(:);
ltx ltx.
Table:T{
CHAPTER \fBBOLD\fR
T}
.TE
.sp
Document short: UNNUMBERED CHAPTER; CHAPTER \fBBOLD\fR\&.
.sp
Document full: UNNUMBERED CHAPTER; Section 3, \(lqChapter \fBbold\fR\(rq; \fIAppendix\fR\&.
.sp
Unset: CHAPTER \fBBOLD\fR; UNNUMBERED CHAPTER; APPENDIX\&.
.sp
Empty: CHAPTER \fBBOLD\fR; UNNUMBERED CHAPTER; \fIAppendix\fR\&.
.sp
Unknown: CHAPTER \fBBOLD\fR; UNNUMBERED CHAPTER; \fIAppendix\fR\&.
.SH "CHAPTER BOLD"
.SS "Ordinary section"
.SH "UNNUMBERED CHAPTER"
.SH "LABELLED CHAPTER"
.SH "APPENDIX"
