[package]
name = "acdc-html"
version.workspace = true
edition.workspace = true
authors.workspace = true
description.workspace = true

[dependencies]
acdc-backends-common.workspace = true
acdc-parser.workspace = true
thiserror.workspace = true
tracing.workspace = true

[lints]
workspace = true
